language: node_js
node_js:
  - "lts/boron"
install:
  - npm install -g gulp
  - npm install -g gulp-cli
  - npm install -g bower
  - npm install
  - bower install
script:
  - npm link gulp
  - gulp build
